# -*- coding: utf-8 -*-
"""Capstone1 - Log Reg Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iv4Wq_zdOeZIPSKbzq5_tI1F78oGTcZg
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
from IPython.display import display
from sklearn.metrics import mutual_info_score
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
from tqdm.auto import tqdm
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score


import seaborn as sns
from matplotlib import pyplot as plt
# %matplotlib inline

import kagglehub

# Download latest version
path = kagglehub.dataset_download("lainguyn123/student-performance-factors")
print("Path to dataset files:", path)

file_path = f"{path}/StudentPerformanceFactors.csv"
df = pd.read_csv(file_path)

# Lower case all column names and replace blanks with _
df.columns = df.columns.str.lower().str.replace(' ','_')

# Delete rows with missing values
df = df.dropna(subset=['teacher_quality'])
df = df.dropna(subset=['parental_education_level'])
df = df.dropna(subset=['distance_from_home'])

# Define high score
df['high_score'] = (df['exam_score'] >= 70).astype(int)

categorical = ['parental_involvement', 'access_to_resources', 'extracurricular_activities', 'motivation_level', 'internet_access','family_income','teacher_quality','school_type','peer_influence','learning_disabilities','parental_education_level','distance_from_home','gender']
numerical = ['hours_studied','attendance','sleep_hours','previous_scores', 'tutoring_sessions','physical_activity']

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=11)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=11)

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.high_score.values
y_val = df_val.high_score.values
y_test = df_test.high_score.values

del df_train['high_score']
del df_train['exam_score']
del df_val['high_score']
del df_val['exam_score']
del df_test['high_score']
del df_test['exam_score']

train_dicts = df_train.to_dict(orient='records')
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)

dicts_val = df_val.to_dict(orient='records')
X_val = dv.transform(dicts_val)

log_reg = LogisticRegression(C=10, max_iter=1000, random_state=1)
log_reg.fit(X_train, y_train)

y_prob_log_reg = log_reg.predict_proba(X_val)[:, 1]  # Probability of positive class
y_pred_log_reg = (y_prob_log_reg >= 0.5).astype(int)

precision_log_reg = precision_score(y_val, y_pred_log_reg)
recall_log_reg = recall_score(y_val, y_pred_log_reg)
f1_log_reg = f1_score(y_val, y_pred_log_reg)
roc_auc_log_reg = roc_auc_score(y_val, y_prob_log_reg)

orig_acc = round((y_val == y_pred_log_reg).mean(),2)
print(orig_acc)

"""SAVE MODEL

"""

import pickle

output = 'Capstone1_Model.bin'
output

with open(output, 'wb') as f_out:
    pickle.dump((dv, log_reg), f_out)

model_file = 'Capstone1_Model.bin'

with open(model_file, 'rb') as f_in:
    dv, log_reg = pickle.load(f_in)

dv,log_reg

Student= {'hours_studied': 30,
          'attendance': 61,
          'parental_involvement': 'High',
          'access_to_resources': 'High',
          'extracurricular_activities': 'No',
          'sleep_hours': 10,
          'previous_scores': 64,
          'motivation_level': 'Low',
          'internet_access': 'Yes',
          'tutoring_sessions': 4,
          'family_income': 'Medium',
          'teacher_quality': 'Medium',
          'school_type': 'Public',
          'peer_influence': 'Positive',
          'physical_activity': 2,
          'learning_disabilities': 'No',
          'parental_education_level': 'Postgraduate',
          'distance_from_home': 'Moderate',
          'gender': 'Male'}

X = dv.transform(Student)

log_reg.predict_proba(X)[0,1]